version: '3.8'

services:
  user-api:
    build: .
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - OpenTelemetry__OtlpEndpoint=http://alloy:4317
    depends_on:
      - alloy
    networks:
      - otel-network

  alloy:
    image: grafana/alloy:latest
    ports:
      - "4317:4317"  # OTLP gRPC receiver
      - "4318:4318"  # OTLP HTTP receiver
      - "12345:12345" # Alloy UI
    volumes:
      - ./alloy.config:/.config/alloy/config.alloy
    command: ["run", "--server.http.listen-addr=0.0.0.0:12345", "--storage.path=/var/lib/alloy/data", "/.config/alloy/config.alloy"]
    networks:
      - otel-network

networks:
  otel-network:
    driver: bridge
